version: "3.8"
services:
  db:
    image: postgres:15
    container_name: flowboard-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flowboard
    volumes:
      - flowboard-data:/var/lib/postgresql/data

volumes:
  flowboard-data:
