services:
  - type: web
    name: flowboard-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://flow-board-peach.vercel.app
      - key: SEED_SAMPLE_DATA
        value: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /health
    autoDeploy: true
